### PR TITLE
fixes #28

### LINKED ISSUE #28: Scroll Buttton
It present in footer section. It should be visible when we start scrolling page
Please assign me

### PR DESCRIPTION
**Pull request by aditya-singh9**
added a scroll to up button which comes when user scrolls the page a little bit and disappears when user goes to the top of the page.

### CODE REVIEW

**Comment by AlexyPulivelil** [comment]
Looks cool. Thanks for the update.

**Comment by aditya-singh9** [comment]
hey @AlexyPulivelil  bro its `hacktoberfest-accepted`   not `hacktoberest-accepted`. Can you please correct this.

**Comment by AlexyPulivelil** [comment]
@aditya-singh9 Thanks for pointing out the mistake. I have corrected it.

**Comment by AlexyPulivelil** [comment]
Sorry bro. Still there is confits. Can you please check
Screenshot 2021-10-03 215341

**Comment by aditya-singh9** [comment]
RESOLVED!!

**Comment by AlexyPulivelil** [comment]
Thanks

**Pull request merged**
