### PR TITLE
Updated expert.html and fixed its Facebook icon too

### PR DESCRIPTION
**Pull request by Sonukumarkeshri4**
issue #36 

please review my PR . I have added Upcoming and past events and it responsive too. 
I have corrected the Facebook icon of footer of the page too.

### CODE REVIEW

**Comment by AlexyPulivelil** [comment]
@Sonukumarkeshri4 Can you please look for the conflicts and add a new PR. Thanks

**Comment by AlexyPulivelil** [comment]
@Sonukumarkeshri4 Can you please look for the conflicts and add a new PR. Thanks

**Comment by Sonukumarkeshri4** [comment]
I have made another PR and that was merged just now
#47

**Comment by AlexyPulivelil** [comment]
> I have made another PR and that was merged just now #47

Yup, so can I close this PR without merging it, I hope you have made all changes in #47

**Comment by Sonukumarkeshri4** [comment]
Yes I've made all changes there, 
you can close this one. 
Thankyou

**Pull request closed without merging**
