### PR TITLE
Update Header and font-style of main heading in the landing page!

### PR DESCRIPTION
**Pull request by vishcomestrue**
Changes made and the reason:

1. Fine-tuned the **header** by **adding class to the logo image** and **justified** the content of the header so that the header looks **clean**. **Reduced the padding** of the list elements since the header took way more space than required which might affect the first impression of targeted audience
2. Changed the **font style of main-heading** displayed in the landing page since it also contributes to first-impression of anyone visiting the site for the first time.

### CODE REVIEW

**Comment by AlexyPulivelil** [comment]
Hey, I'm afraid I couldn't' merge this PR. Please work on this and make the changes
Screenshot 2021-10-02 204000

**Comment by AlexyPulivelil** [comment]
@vishcomestrue Hey, are you working on this. If so please give a reply. Otherwise I can close this issue and change the tag to **invalid**. Thanks

**Comment by vishcomestrue** [comment]
Yes, I am working on it but I need more time!

**Comment by AlexyPulivelil** [comment]
@vishcomestrue Thanks a lot for the response. Take your time. No need to make changes immediately. But also check for the conflicts. Thanks

**Pull request closed without merging**
