### PR TITLE
bg img height and scrollbar changes

### PR DESCRIPTION
**Pull request by SayantaniDeb**
Issue #3 
the changes are made.

https://user-images.githubusercontent.com/74983536/135647803-e4c46e72-3b57-45e4-86f3-cce467ee4b61.mp4

### CODE REVIEW

**Comment by AlexyPulivelil** [comment]
I'm afraid that I couldn't merge this PR. Now the background is covering the entire page. Can you check for any other changes.

**Comment by SayantaniDeb** [comment]
What about the scrollbar colour change?

**Comment by AlexyPulivelil** [comment]
@SayantaniDeb The present colour is formal I guess, if you could make it more attractive it will be great. Thanks

**Comment by AlexyPulivelil** [comment]
@SayantaniDeb Since this PR is having conflicts, i'm closing this out. If you have any other suggestion please open a new issue. I'm labeling this PR as **invalid** Thanks

**Review by AlexyPulivelil — COMMENTED** [review]
Since this is having conflicts, it can't be merged

**Comment by SayantaniDeb** [comment]
Please don't label it as invalid, just don't approve it. Cause having a
labelled PR which says invalid means I made spam changes. Which isn't true.
:')
If you don't label it as hacktoberfest-accepted or merge it it's still
same. I won't get marked for it in hacktoberfest. Also, just close the PR
no need to label it as invalid.

**Comment by AlexyPulivelil** [comment]
Done

**Pull request closed without merging**
